name: p2p_chat
description: Chat P2P seguro com encriptação total (ponta a ponta + local)

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  shared_preferences: ^2.2.2
  sqflite_sqlcipher: ^2.3.3      # Base de dados cifrada
  cryptography: ^2.7.0           # Criptografia moderna (Curve25519, AES-GCM)
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
